import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertTriangle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";

export default function Disclaimer() {
  return (
    <div className="min-h-screen p-4 md:p-8 bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <AlertTriangle className="w-16 h-16 mx-auto mb-4 text-purple-600" />
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent mb-2">
            Disclaimer
          </h1>
          <p className="text-gray-600">Important information about DreamScape services</p>
        </div>

        <Alert className="mb-6 bg-yellow-50 border-yellow-200">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription className="text-yellow-800">
            <strong>Important:</strong> DreamScape services are for entertainment and personal reflection purposes only. They should not replace professional advice.
          </AlertDescription>
        </Alert>

        <Card className="bg-white/60 backdrop-blur-sm border-white/20">
          <CardHeader>
            <CardTitle>DreamScape Service Disclaimer</CardTitle>
          </CardHeader>
          <CardContent className="prose max-w-none">
            <div className="space-y-6 text-gray-700">
              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">1. Entertainment Purposes Only</h3>
                <p>All services provided by DreamScape, including but not limited to dream interpretation, tarot readings, astrology charts, horoscopes, rune readings, and fortune telling, are intended for entertainment, personal reflection, and educational purposes only. They are not intended to provide professional advice of any kind.</p>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">2. Not Professional Advice</h3>
                <p>DreamScape services should never be used as a substitute for:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Medical advice, diagnosis, or treatment</li>
                  <li>Mental health counseling or therapy</li>
                  <li>Legal counsel or advice</li>
                  <li>Financial planning or investment advice</li>
                  <li>Career counseling or professional guidance</li>
                  <li>Relationship therapy or counseling</li>
                </ul>
                <p className="mt-3">Always consult qualified professionals for serious health, legal, financial, or personal matters.</p>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">3. AI-Generated Content</h3>
                <p>Our interpretations and readings are generated by artificial intelligence systems trained on various mystical and spiritual traditions. While sophisticated, these systems:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Cannot predict the future with certainty</li>
                  <li>May produce inconsistent results</li>
                  <li>Are based on programmed algorithms, not supernatural powers</li>
                  <li>Should be viewed as creative interpretations, not absolute truth</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">4. No Guarantees</h3>
                <p>DreamScape makes no warranties or guarantees regarding:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The accuracy of any reading or interpretation</li>
                  <li>The fulfillment of any predictions or guidance</li>
                  <li>Positive outcomes from following our suggestions</li>
                  <li>The resolution of personal problems or challenges</li>
                  <li>Compatibility with any specific belief system</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">5. Personal Responsibility</h3>
                <p>By using DreamScape, you acknowledge that:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You are responsible for your own decisions and actions</li>
                  <li>You will not rely solely on our services for important life decisions</li>
                  <li>You understand the limitations of AI-generated content</li>
                  <li>You will seek professional help when appropriate</li>
                  <li>You use our services at your own risk</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">6. Cultural and Religious Considerations</h3>
                <p>DreamScape draws from various mystical and spiritual traditions. We respect that:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Not all interpretations align with every belief system</li>
                  <li>Our content may conflict with your religious views</li>
                  <li>Cultural context affects interpretation accuracy</li>
                  <li>Personal beliefs should take precedence over our suggestions</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">7. Age Restrictions</h3>
                <p>DreamScape is intended for users 13 years and older. Parents and guardians should:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Supervise minor children's use of the service</li>
                  <li>Discuss the entertainment nature of our content</li>
                  <li>Ensure children don't make important decisions based on readings</li>
                  <li>Seek professional help for children's serious concerns</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">8. Mental Health Considerations</h3>
                <p>If you are experiencing:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Depression, anxiety, or other mental health issues</li>
                  <li>Thoughts of self-harm or suicide</li>
                  <li>Substance abuse problems</li>
                  <li>Severe life crises or trauma</li>
                </ul>
                <p className="mt-3">Please seek help from qualified mental health professionals immediately. In emergencies, call your local emergency services or suicide prevention hotline.</p>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">9. Limitation of Liability</h3>
                <p>DreamScape and its operators shall not be liable for:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Decisions made based on our interpretations or readings</li>
                  <li>Any negative outcomes from following our suggestions</li>
                  <li>Emotional distress caused by our content</li>
                  <li>Financial losses related to our guidance</li>
                  <li>Relationship or personal problems arising from our services</li>
                </ul>
              </section>

              <section>
                <h3 className="text-xl font-semibold text-purple-700 mb-3">10. Contact Information</h3>
                <p>If you have questions about this disclaimer or concerns about our services, please contact us at:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Email: support@dreamscape.app</li>
                  <li>Include "Disclaimer Question" in the subject line</li>
                  <li>We'll respond within 24 hours</li>
                </ul>
              </section>

              <div className="bg-purple-50 p-6 rounded-lg border border-purple-200 mt-8">
                <h4 className="text-lg font-semibold text-purple-800 mb-2">Remember:</h4>
                <p className="text-purple-700">
                  DreamScape is designed to inspire self-reflection, creativity, and personal growth. Use our services as a tool for entertainment and introspection, but always trust your own judgment and seek professional help when needed.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}